name: 11 - Working with Inputs

on:
    workflow_dispatch:
        inputs:
            dry-run:
                description: Skip deployment and only print build output
                type: boolean
                default: false
            target:
                description: Which environment the workflow will target
                type: environment
                required: true
            tag:
                type: choice
                options:
                    - v1
                    - v2
                    - v3
                default: v3
                description: Release from which to build and deploy

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Build
              run: echo "Building from tag ${{ inputs.tag }}"
    build:
        runs-on: ubuntu-latest
        if: ${{ !inputs.dry-run }}
        steps:
            - name: Deploy
              run: echo "Deploying to ${{ inputs.target }}"
